layer.conf: improve LAYERDEPENDS; LAYERRECOMMENDS
The documentation properly mentions that meta-oe (openembedded-layer)
is a layer dependency, but it is missing from conf/layer.conf

When adding meta-homeassistant with bitbake-layers layerindex-fetch it
would properly dynamically detect this (because of meta-python setting
LAYERDEPENDS), but currently the layerindex https://layers.openembedded.org/
does not recurse LAYERDEPENDS.

Currently, the meta-oe dependency is set in the layerindex, but since
it is not in conf/layer.conf a warning is thrown:

WARNING: Dependencies "<QuerySet [<LayerDependency: meta-homeassistant
         depends on meta-oe>]>" are not in meta-homeassistant's
	 conf/layer.conf
WARNING: Either set REMOVE_LAYER_DEPENDENCIES to remove them from the
         database, or fix conf/layer.conf

When attempting to parse the recipes in dynamic-layers/swupdate, the
layerindex will also fail if meta-swupdate is not checkout out, which
can be fixed by adding LAYERRECOMMENDS.

bb.parse.ParseError: ParseError at
  /opt/workdir/https___github_com_meta-homeassistant_meta-homeassistant_git/
  dynamic-layers/swupdate/recipes-images/swus/
  update-image-core-image-homeassistant.bb:6:
  Could not inherit file classes/swupdate.bbclass

Signed-off-by: Tim Orling <tim.orling@konsulko.com>