kas: renamed LICENSE_FLAGS_WHITELIST to LICENSE_FLAGS_ACCEPTED
Somewhere in the history of Yocto this variable was renamed.

Fixed:
  ERROR: Variable LICENSE_FLAGS_WHITELIST has been renamed to LICENSE_FLAGS_ACCEPTED

Signed-off-by: Jan Vermaete <jan.vermaete@gmail.com>